INSERT INTO `unidades_medida` (codigo, descripcion) VALUES
('4A', 'BOBINAS'),
('BJ', 'BALDE'),
('BLL', 'BARRILES'),
('BG', 'BOLSA'),
('BO', 'BOTELLAS'),
('BX', 'CAJA'),
('CT', 'CARTONES'),
('CMT', 'CENTIMETRO'),
('CEN', 'CIENTO DE UNIDADES'),
('CY', 'CILINDRO'),
('DZN', 'DOCENA'),
('DZP', 'DOCENA POR PAQUETE'),
('BE', 'FARDO'),
('GLL', 'GALON US'),
('GRM', 'GRAMO'),
('KGM', 'KILOGRAMO'),
('KIT', 'KIT'),
('LBR', 'LIBRAS'),
('LTR', 'LITRO'),
('MTR', 'METRO'),
('MTK', 'METRO CUADRADO'),
('MTQ', 'METRO CUBICO'),
('MGM', 'MILIGRAMOS'),
('MLT', 'MILILITRO'),
('MMT', 'MILIMETRO'),
('MMK', 'MILIMETRO CUADRADO'),
('MMQ', 'MILIMETRO CUBICO'),
('MIL', 'MILLARES'),
('UM', 'MILLON DE UNIDADES'),
('ONZ', 'ONZAS'),
('PK', 'PAQUETE'),
('PR', 'PAR'),
('FOT', 'PIES'),
('FTK', 'PIES CUADRADOS'),
('FTQ', 'PIES CUBICOS'),
('C62', 'PIEZAS'),
('PG', 'PLACAS'),
('ST', 'PLIEGO'),
('INH', 'PULGADAS'),
('RM', 'RESMA'),
('SA', 'SACO'),
('TNE', 'TONELADA'),
('NIU', 'UNIDAD (BIENES)'),
('ZZ', 'UNIDAD (SERVICIOS)'),
('YRD', 'YARDA'),
('HUR', 'HORA');