name: mobile_app
description: Aplicación móvil para el sistema de gestión de restaurantes.

# Prevenir publicaciones accidentales en pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Paquete para realizar peticiones HTTP a la API.
  http: ^0.13.4

  # Iconos de Cupertino (opcional, pero buena práctica).
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter para mantener un código limpio y consistente.
  flutter_lints: ^1.0.0

# La siguiente sección es específica de Flutter.
flutter:
  # La siguiente línea asegura que la fuente Material Icons esté incluida.
  uses-material-design: true

  # Para añadir assets a tu aplicación, descomenta y ajusta esta sección.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
